### ISSUE TITLE
Modify current structure

### ISSUE THREAD

**Issue by williamluang** [shadonovitch/dird-project-back#30]
Modify current structure to a more readable one
- isolate validator
- isolate routing

**Comment by williamluang** [comment]
Now we use Router inside multiples routes fil
- export each route function
- single route file with all routes

**Comment by williamluang** [comment]
@shadonovitch when you have time can you check the branch `hotfix/modify-struct`

I isolated components on chat features. Can you give me some feedback when can ?
I feel like it is better organized this way, each component is isolated from each other so it is more clear, at least for me.

**Comment by williamluang** [comment]
If you think this is useless, well i'll just get over it and do something else !

**Comment by shadonovitch** [comment]
I don't think what you tried to accomplish by separating routers and their function is appropriate. I've never seen a single Koa project doing that, and I think it impairs the readability of the routes. Although, the validators can be moved to their own file that would regroup each of them (a validators.js file in the routes/ directory) since we're going to have 3-4  validators tops.
